name: Java Main Class Execution

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: 20
        
    - name: Compile and Execute Java Main Class
      run: mvn compile exec:java
