name: Selenium Tests on Staging Branch

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      firefox:
        image: selenium/standalone-firefox:latest
        options: --shm-size=2g  # Adjust shared memory size as needed

    steps:
      # Checkout the code from the staging branch
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: staging

      # Set up Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Maven
      - name: Set up Maven
        uses: s4u/maven-settings-action@v2

      # Install Allure
      - name: Install Allure
        run: |
          ALLURE_VERSION=2.29.0
          wget -qO- https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz | tar -zx -C /opt/
          sudo ln -s /opt/allure-${ALLURE_VERSION}/bin/allure /usr/bin/allure

      # Verify Java, Maven, and Allure installation
      - name: Verify installations
        run: |
          java -version
          mvn -version
          allure --version

      # Run tests
      - name: Run tests
        run: mvn compile exec:java
